// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RpgFight.Data;

#nullable disable

namespace RpgFight.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230408013647_UserRelatedBattleModels")]
    partial class UserRelatedBattleModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RpgFight.Models.Armor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Armors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warrior Armor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mage Robe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fur Armor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Full Plate Armor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Royal Armor"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Necromancer Robe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Heavenly Armor"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cursed Armor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Arch Mage Mask"
                        });
                });

            modelBuilder.Entity("RpgFight.Models.BattleCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoint")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WeaponId");

                    b.ToTable("BattleCharacters");
                });

            modelBuilder.Entity("RpgFight.Models.BattleCharacterEffect", b =>
                {
                    b.Property<int>("BattleCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("EffectId")
                        .HasColumnType("int");

                    b.HasKey("BattleCharacterId", "EffectId");

                    b.HasIndex("EffectId");

                    b.ToTable("BattleCharacterEffects");
                });

            modelBuilder.Entity("RpgFight.Models.BattleEnemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoint")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WeaponId");

                    b.ToTable("BattleEnemies");
                });

            modelBuilder.Entity("RpgFight.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("HitPoint")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WeaponId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("RpgFight.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefenseModifier")
                        .HasColumnType("int");

                    b.Property<int>("HitPointModifier")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrengthModifier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Classs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefenseModifier = 5,
                            HitPointModifier = 15,
                            IntelligenceModifier = 5,
                            Name = "Knight",
                            StrengthModifier = 5
                        },
                        new
                        {
                            Id = 2,
                            DefenseModifier = 10,
                            HitPointModifier = 10,
                            IntelligenceModifier = 0,
                            Name = "Crusader",
                            StrengthModifier = 10
                        },
                        new
                        {
                            Id = 3,
                            DefenseModifier = -5,
                            HitPointModifier = 10,
                            IntelligenceModifier = -5,
                            Name = "Berserker",
                            StrengthModifier = 30
                        },
                        new
                        {
                            Id = 4,
                            DefenseModifier = -5,
                            HitPointModifier = 10,
                            IntelligenceModifier = 30,
                            Name = "Mage",
                            StrengthModifier = -5
                        },
                        new
                        {
                            Id = 5,
                            DefenseModifier = 10,
                            HitPointModifier = 10,
                            IntelligenceModifier = 20,
                            Name = "Witch",
                            StrengthModifier = -10
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Effect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Self")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Effects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 1,
                            Intensity = 10,
                            Name = "Flames",
                            Self = false
                        },
                        new
                        {
                            Id = 2,
                            Duration = 1,
                            Intensity = 10,
                            Name = "Ice",
                            Self = false
                        },
                        new
                        {
                            Id = 3,
                            Duration = 1,
                            Intensity = 10,
                            Name = "Sparks",
                            Self = false
                        },
                        new
                        {
                            Id = 4,
                            Duration = 1,
                            Intensity = 10,
                            Name = "Heal I",
                            Self = true
                        },
                        new
                        {
                            Id = 5,
                            Duration = 1,
                            Intensity = 20,
                            Name = "Heal II",
                            Self = true
                        },
                        new
                        {
                            Id = 6,
                            Duration = 1,
                            Intensity = 30,
                            Name = "Heal III",
                            Self = true
                        },
                        new
                        {
                            Id = 7,
                            Duration = -1,
                            Intensity = 15,
                            Name = "Frenzy",
                            Self = true
                        },
                        new
                        {
                            Id = 8,
                            Duration = 1,
                            Intensity = -15,
                            Name = "Lethargy",
                            Self = false
                        },
                        new
                        {
                            Id = 9,
                            Duration = -1,
                            Intensity = 15,
                            Name = "Wisdom",
                            Self = true
                        },
                        new
                        {
                            Id = 10,
                            Duration = 1,
                            Intensity = -15,
                            Name = "Folly",
                            Self = false
                        },
                        new
                        {
                            Id = 11,
                            Duration = -1,
                            Intensity = 15,
                            Name = "Endurance",
                            Self = true
                        },
                        new
                        {
                            Id = 12,
                            Duration = 1,
                            Intensity = -15,
                            Name = "Weakness",
                            Self = false
                        },
                        new
                        {
                            Id = 13,
                            Duration = -1,
                            Intensity = 10,
                            Name = "Riposite",
                            Self = true
                        },
                        new
                        {
                            Id = 14,
                            Duration = -1,
                            Intensity = 10,
                            Name = "Protection I",
                            Self = true
                        },
                        new
                        {
                            Id = 15,
                            Duration = -1,
                            Intensity = 20,
                            Name = "Protection II",
                            Self = true
                        },
                        new
                        {
                            Id = 16,
                            Duration = -1,
                            Intensity = 30,
                            Name = "Protection III",
                            Self = true
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("HitPoint")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmorId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SkillId");

                    b.HasIndex("WeaponId");

                    b.ToTable("Enemies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Defense = 5,
                            HitPoint = 200,
                            Intelligence = 10,
                            Name = "Tippy-toe Jack",
                            Strength = 15
                        },
                        new
                        {
                            Id = 2,
                            Defense = 10,
                            HitPoint = 200,
                            Intelligence = 15,
                            Name = "Blair Witch",
                            Strength = 5
                        },
                        new
                        {
                            Id = 3,
                            Defense = 15,
                            HitPoint = 250,
                            Intelligence = 5,
                            Name = "Holy Warrior",
                            Strength = 10
                        },
                        new
                        {
                            Id = 4,
                            Defense = 10,
                            HitPoint = 300,
                            Intelligence = 20,
                            Name = "Shadow Wizzard",
                            Strength = 0
                        },
                        new
                        {
                            Id = 5,
                            Defense = 5,
                            HitPoint = 350,
                            Intelligence = 5,
                            Name = "Ragnar",
                            Strength = 20
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Joins.ArmorEffect", b =>
                {
                    b.Property<int>("ArmorId")
                        .HasColumnType("int");

                    b.Property<int>("EffectId")
                        .HasColumnType("int");

                    b.HasKey("ArmorId", "EffectId");

                    b.HasIndex("EffectId");

                    b.ToTable("ArmorEffects");

                    b.HasData(
                        new
                        {
                            ArmorId = 1,
                            EffectId = 14
                        },
                        new
                        {
                            ArmorId = 1,
                            EffectId = 11
                        },
                        new
                        {
                            ArmorId = 2,
                            EffectId = 1
                        },
                        new
                        {
                            ArmorId = 2,
                            EffectId = 14
                        },
                        new
                        {
                            ArmorId = 3,
                            EffectId = 7
                        },
                        new
                        {
                            ArmorId = 3,
                            EffectId = 10
                        },
                        new
                        {
                            ArmorId = 4,
                            EffectId = 15
                        },
                        new
                        {
                            ArmorId = 4,
                            EffectId = 11
                        },
                        new
                        {
                            ArmorId = 5,
                            EffectId = 16
                        },
                        new
                        {
                            ArmorId = 5,
                            EffectId = 10
                        },
                        new
                        {
                            ArmorId = 6,
                            EffectId = 14
                        },
                        new
                        {
                            ArmorId = 6,
                            EffectId = 9
                        },
                        new
                        {
                            ArmorId = 7,
                            EffectId = 16
                        },
                        new
                        {
                            ArmorId = 7,
                            EffectId = 9
                        },
                        new
                        {
                            ArmorId = 7,
                            EffectId = 11
                        },
                        new
                        {
                            ArmorId = 8,
                            EffectId = 14
                        },
                        new
                        {
                            ArmorId = 8,
                            EffectId = 13
                        },
                        new
                        {
                            ArmorId = 8,
                            EffectId = 12
                        },
                        new
                        {
                            ArmorId = 9,
                            EffectId = 15
                        },
                        new
                        {
                            ArmorId = 9,
                            EffectId = 13
                        },
                        new
                        {
                            ArmorId = 9,
                            EffectId = 9
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Joins.BattleEnemyEffect", b =>
                {
                    b.Property<int>("BattleEnemyId")
                        .HasColumnType("int");

                    b.Property<int>("EffectId")
                        .HasColumnType("int");

                    b.HasKey("BattleEnemyId", "EffectId");

                    b.HasIndex("EffectId");

                    b.ToTable("BattleEnemyEffects");
                });

            modelBuilder.Entity("RpgFight.Models.Joins.SkillEffect", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("EffectId")
                        .HasColumnType("int");

                    b.HasKey("SkillId", "EffectId");

                    b.HasIndex("EffectId");

                    b.ToTable("SkillEffects");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            EffectId = 4
                        },
                        new
                        {
                            SkillId = 2,
                            EffectId = 1
                        },
                        new
                        {
                            SkillId = 3,
                            EffectId = 2
                        },
                        new
                        {
                            SkillId = 4,
                            EffectId = 3
                        },
                        new
                        {
                            SkillId = 5,
                            EffectId = 5
                        },
                        new
                        {
                            SkillId = 6,
                            EffectId = 1
                        },
                        new
                        {
                            SkillId = 6,
                            EffectId = 2
                        },
                        new
                        {
                            SkillId = 7,
                            EffectId = 2
                        },
                        new
                        {
                            SkillId = 7,
                            EffectId = 3
                        },
                        new
                        {
                            SkillId = 8,
                            EffectId = 1
                        },
                        new
                        {
                            SkillId = 8,
                            EffectId = 3
                        },
                        new
                        {
                            SkillId = 9,
                            EffectId = 6
                        },
                        new
                        {
                            SkillId = 10,
                            EffectId = 1
                        },
                        new
                        {
                            SkillId = 10,
                            EffectId = 2
                        },
                        new
                        {
                            SkillId = 10,
                            EffectId = 3
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Joins.WeaponEffect", b =>
                {
                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.Property<int>("EffectId")
                        .HasColumnType("int");

                    b.HasKey("WeaponId", "EffectId");

                    b.HasIndex("EffectId");

                    b.ToTable("WeaponEffects");

                    b.HasData(
                        new
                        {
                            WeaponId = 1,
                            EffectId = 8
                        },
                        new
                        {
                            WeaponId = 2,
                            EffectId = 10
                        },
                        new
                        {
                            WeaponId = 4,
                            EffectId = 9
                        },
                        new
                        {
                            WeaponId = 5,
                            EffectId = 11
                        },
                        new
                        {
                            WeaponId = 6,
                            EffectId = 7
                        },
                        new
                        {
                            WeaponId = 7,
                            EffectId = 8
                        },
                        new
                        {
                            WeaponId = 7,
                            EffectId = 11
                        },
                        new
                        {
                            WeaponId = 8,
                            EffectId = 7
                        },
                        new
                        {
                            WeaponId = 8,
                            EffectId = 10
                        },
                        new
                        {
                            WeaponId = 9,
                            EffectId = 13
                        },
                        new
                        {
                            WeaponId = 9,
                            EffectId = 8
                        });
                });

            modelBuilder.Entity("RpgFight.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 0,
                            Name = "Heal I"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 25,
                            Name = "Flames"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 25,
                            Name = "Ice Spike"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 25,
                            Name = "Eletric Shock"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 0,
                            Name = "Heal II"
                        },
                        new
                        {
                            Id = 6,
                            Damage = 50,
                            Name = "Thermal Shock"
                        },
                        new
                        {
                            Id = 7,
                            Damage = 50,
                            Name = "Cold Storm"
                        },
                        new
                        {
                            Id = 8,
                            Damage = 50,
                            Name = "Eletric Fire"
                        },
                        new
                        {
                            Id = 9,
                            Damage = 0,
                            Name = "Heal III"
                        },
                        new
                        {
                            Id = 10,
                            Damage = 75,
                            Name = "Elemental Burst"
                        });
                });

            modelBuilder.Entity("RpgFight.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RpgFight.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Damage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Weapons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Damage = 30,
                            Name = "Clunky Longsword"
                        },
                        new
                        {
                            Id = 2,
                            Damage = 25,
                            Name = "Ugly Knife"
                        },
                        new
                        {
                            Id = 3,
                            Damage = 25,
                            Name = "Sword"
                        },
                        new
                        {
                            Id = 4,
                            Damage = 50,
                            Name = "Assassins Blade"
                        },
                        new
                        {
                            Id = 5,
                            Damage = 50,
                            Name = "Blessed Sword"
                        },
                        new
                        {
                            Id = 6,
                            Damage = 50,
                            Name = "Scimitar"
                        },
                        new
                        {
                            Id = 7,
                            Damage = 75,
                            Name = "Heavy Axe"
                        },
                        new
                        {
                            Id = 8,
                            Damage = 75,
                            Name = "Blessed Sword"
                        },
                        new
                        {
                            Id = 9,
                            Damage = 75,
                            Name = "Sword and Shield"
                        });
                });

            modelBuilder.Entity("RpgFight.Models.BattleCharacter", b =>
                {
                    b.HasOne("RpgFight.Models.Armor", "Armor")
                        .WithMany()
                        .HasForeignKey("ArmorId");

                    b.HasOne("RpgFight.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("RpgFight.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.HasOne("RpgFight.Models.User", "User")
                        .WithOne("BattleCharacters")
                        .HasForeignKey("RpgFight.Models.BattleCharacter", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId");

                    b.Navigation("Armor");

                    b.Navigation("Class");

                    b.Navigation("Skill");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("RpgFight.Models.BattleCharacterEffect", b =>
                {
                    b.HasOne("RpgFight.Models.BattleCharacter", "BattleCharacter")
                        .WithMany("BattleCharacterEffects")
                        .HasForeignKey("BattleCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Effect", "Effect")
                        .WithMany("BattleCharacterEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleCharacter");

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("RpgFight.Models.BattleEnemy", b =>
                {
                    b.HasOne("RpgFight.Models.Armor", "Armor")
                        .WithMany()
                        .HasForeignKey("ArmorId");

                    b.HasOne("RpgFight.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("RpgFight.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.HasOne("RpgFight.Models.User", "User")
                        .WithOne("BattleEnemys")
                        .HasForeignKey("RpgFight.Models.BattleEnemy", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId");

                    b.Navigation("Armor");

                    b.Navigation("Class");

                    b.Navigation("Skill");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("RpgFight.Models.Character", b =>
                {
                    b.HasOne("RpgFight.Models.Armor", "Armor")
                        .WithMany("Characters")
                        .HasForeignKey("ArmorId");

                    b.HasOne("RpgFight.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("RpgFight.Models.Skill", "Skill")
                        .WithMany("Characters")
                        .HasForeignKey("SkillId");

                    b.HasOne("RpgFight.Models.User", "User")
                        .WithOne("Characters")
                        .HasForeignKey("RpgFight.Models.Character", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Weapon", "Weapon")
                        .WithMany("Characters")
                        .HasForeignKey("WeaponId");

                    b.Navigation("Armor");

                    b.Navigation("Class");

                    b.Navigation("Skill");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("RpgFight.Models.Enemy", b =>
                {
                    b.HasOne("RpgFight.Models.Armor", "Armor")
                        .WithMany()
                        .HasForeignKey("ArmorId");

                    b.HasOne("RpgFight.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("RpgFight.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.HasOne("RpgFight.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId");

                    b.Navigation("Armor");

                    b.Navigation("Class");

                    b.Navigation("Skill");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("RpgFight.Models.Joins.ArmorEffect", b =>
                {
                    b.HasOne("RpgFight.Models.Armor", "Armor")
                        .WithMany("ArmorEffects")
                        .HasForeignKey("ArmorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Effect", "Effect")
                        .WithMany("ArmorEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armor");

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("RpgFight.Models.Joins.BattleEnemyEffect", b =>
                {
                    b.HasOne("RpgFight.Models.BattleEnemy", "BattleEnemy")
                        .WithMany("BattleEnemyEffects")
                        .HasForeignKey("BattleEnemyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Effect", "Effect")
                        .WithMany("BattleEnemyEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BattleEnemy");

                    b.Navigation("Effect");
                });

            modelBuilder.Entity("RpgFight.Models.Joins.SkillEffect", b =>
                {
                    b.HasOne("RpgFight.Models.Effect", "Effect")
                        .WithMany("SkillEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Skill", "Skill")
                        .WithMany("SkillEffects")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("RpgFight.Models.Joins.WeaponEffect", b =>
                {
                    b.HasOne("RpgFight.Models.Effect", "Effect")
                        .WithMany("WeaponEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RpgFight.Models.Weapon", "Weapon")
                        .WithMany("WeaponEffects")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Effect");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("RpgFight.Models.Armor", b =>
                {
                    b.Navigation("ArmorEffects");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RpgFight.Models.BattleCharacter", b =>
                {
                    b.Navigation("BattleCharacterEffects");
                });

            modelBuilder.Entity("RpgFight.Models.BattleEnemy", b =>
                {
                    b.Navigation("BattleEnemyEffects");
                });

            modelBuilder.Entity("RpgFight.Models.Effect", b =>
                {
                    b.Navigation("ArmorEffects");

                    b.Navigation("BattleCharacterEffects");

                    b.Navigation("BattleEnemyEffects");

                    b.Navigation("SkillEffects");

                    b.Navigation("WeaponEffects");
                });

            modelBuilder.Entity("RpgFight.Models.Skill", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("SkillEffects");
                });

            modelBuilder.Entity("RpgFight.Models.User", b =>
                {
                    b.Navigation("BattleCharacters");

                    b.Navigation("BattleEnemys");

                    b.Navigation("Characters");
                });

            modelBuilder.Entity("RpgFight.Models.Weapon", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("WeaponEffects");
                });
#pragma warning restore 612, 618
        }
    }
}
